"""Final_database_design

Revision ID: 18783dab0ba4
Revises: 
Create Date: 2025-04-07 15:35:29.390579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18783dab0ba4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('aux_sensors_data')
    op.drop_constraint('sensors_auxSensorID_fkey', 'sensors', type_='foreignkey')
    op.drop_column('sensors', 'auxSensorID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('auxSensorID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sensors_auxSensorID_fkey', 'sensors', 'aux_sensors_data', ['auxSensorID'], ['id'])
    op.create_table('aux_sensors_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='aux_sensors_data_pkey')
    )
    op.drop_table('aux_sensors')
    # ### end Alembic commands ###
