"""Initial migration for redesigned database

Revision ID: 75a6f7623abc
Revises: 75ed907ebc89
Create Date: 2025-03-19 14:39:42.831318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a6f7623abc'
down_revision: Union[str, None] = '75ed907ebc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
