"""Add streaming and old data hiding support

Revision ID: 75ed907ebc89
Revises: b409bffa6c9b
Create Date: 2024-11-07 22:18:34.547023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ed907ebc89'
down_revision: Union[str, None] = 'b409bffa6c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_datas', sa.Column('hiddenDataIndices', postgresql.ARRAY(sa.Integer()), nullable=False, server_default="{}"))
    op.add_column('events', sa.Column('isStreaming', sa.Boolean(), nullable=False, server_default=text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'isStreaming')
    op.drop_column('device_datas', 'hiddenDataIndices')
    # ### end Alembic commands ###
